# Generated by Django 3.1.3 on 2021-01-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
    ]
